[package]
name = "engine"
version = "4.1.0"
edition = "2021"
rust-version = "1.83"

[features]
release = []

[build-dependencies]
cc = "1.1.37"

[dependencies]
arrayvec = "0.7.6"
colored = "2.1.0"
nom = "7.1.1"
rand = "0.8.5"

[dev-dependencies]
paste = "1.0.15"

[lints.rust]
future_incompatible = "warn"
let_underscore = "warn"
nonstandard_style = "warn"
rust_2018_idioms = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

wildcard_imports = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
option_if_let_else = "allow"
module_name_repetitions = "allow"
inline_always = "allow"
missing_const_for_fn = "allow"
too_many_arguments = "allow"
too_many_lines = "allow"
cognitive_complexity = "allow"
must_use_candidate = "allow"
return_self_not_must_use = "allow"
type_complexity = "allow"
let_and_return = "allow"
significant_drop_tightening = "allow"
enum_glob_use = "allow"

allow_attributes = "warn"
allow_attributes_without_reason = "warn"

[profile.release]
# debug = 1
panic = "abort"
codegen-units = 1
lto = true
