[workspace]
members = [
    "chess",
    "engine",
]

resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
rust-version = "1.71"

[workspace.dependencies]
color-eyre = { version = "0.6.2", default-features = false }
nom = "7.1.1"
rand = "0.8.5"

[profile.release]
debug = 1
incremental = true
