[package]
name = "chess"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
color-eyre = { workspace = true }
nom = { workspace = true }
rand = { workspace = true }
