[package]
name = "engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
git-version = "0.3.8"
chess = { path = "../chess" }
clap = { workspace = true }
nom = { workspace = true }
rand = { workspace = true }

[lib]
name = "engine"
path = "src/lib.rs"

[[bin]]
name = "engine"
path = "src/main.rs"
