[package]
name = "engine"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
git-version = "0.3.8"
chess = { path = "../chess" }
clap = { version = "3.1.8", features = ["derive"] }
nom = "7.1.1"

[lib]
name = "engine"
path = "src/lib.rs"

[[bin]]
name = "engine"
path = "src/main.rs"
