[package]
name = "engine_win_at_chess_tests"
version = "0.1.0"

[workspace]

[dependencies]
tcheran = { path = "../.." }
color-eyre = { version = "0.6.2", default-features = false }

[[bin]]
name = "engine_win_at_chess_tests"
path = "main.rs"
